kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend-deployment
  namespace: chatapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend-pod
      namespace: chatapp
      labels:
        app: backend
    spec:
      containers:
      - name: chatapp-backend
        image: saleemclavax/chatapp-backend:latest
        ports: 
        - containerPort: 5001
        env:
        - name: NODE_ENV
          value: production
        - name : MONGODB_URI
          value : "mongodb://mongoadmin:secret@mongo-service:27017/dbname?authSource=admin"
        - name : JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: chat-app-secrets
              key: jwt
        - name : PORT 
          value : "5001"     
        


