kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend-deployment
  namespace: chatapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend-pod
      namespace: chatapp
      labels:
        app: frontend
    spec:
      containers:
      - name: chatapp-frontend
        image: saleemclavax/chatapp-frontend:latest
        ports: 
        - containerPort: 80
        env:
        - name: NODE_ENV
          value: production


